# **1. Load and Understand Dataset**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

file_path = "/content/drive/MyDrive/Healthcare_Analytics/diabetic_data.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 101766
Columns: 50

# **CLEANING DATASET**

In [3]:
clean_df = df.copy()

print("Cleaning copy created!")
print(clean_df.shape)

Cleaning copy created!
(101766, 50)

In [4]:
missing_report = pd.DataFrame({
    "Question_Mark": clean_df.isin(["?"]).sum(),
    "NaN": clean_df.isnull().sum()
})

missing_report = missing_report[
    (missing_report["Question_Mark"] > 0) |
    (missing_report["NaN"] > 0)
]

missing_report

                   Question_Mark    NaN
race                        2273      0
weight                     98569      0
payer_code                 40256      0
medical_specialty          49949      0
diag_1                        21      0
diag_2                       358      0
diag_3                      1423      0
max_glu_serum                  0  96420
A1Cresult                      0  84748

In [5]:
clean_df = clean_df.replace("?", np.nan)

print("Unknown values converted to NaN.")

Unknown values converted to NaN.

In [6]:
missing_percent = clean_df.isnull().mean() * 100

missing_percent = missing_percent[missing_percent > 0].sort_values(ascending=False)

missing_percent

weight               96.858479
max_glu_serum        94.746772
A1Cresult            83.277322
medical_specialty    49.082208
payer_code           39.557416
race                  2.233555
diag_3                1.398306
diag_2                0.351787
diag_1                0.020636
dtype: float64

In [7]:
high_missing_cols = [
    "weight",
    "max_glu_serum",
    "A1Cresult",
    "medical_specialty",
    "payer_code"
]

clean_df = clean_df.drop(columns=high_missing_cols)

print("Removed columns:", high_missing_cols)
print("New shape:", clean_df.shape)

Removed columns: ['weight', 'max_glu_serum', 'A1Cresult', 'medical_specialty', 'payer_code']
New shape: (101766, 45)

In [8]:
categorical_missing_cols = [
    "race",
    "diag_1",
    "diag_2",
    "diag_3"
]

clean_df[categorical_missing_cols] = clean_df[categorical_missing_cols].fillna("Unknown")

print("Remaining missing values:")
print(clean_df.isnull().sum().sum())

Remaining missing values:
0

In [9]:
duplicate_count = clean_df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [10]:
clean_df["readmitted"].value_counts()

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [11]:
clean_df["readmitted_30"] = clean_df["readmitted"].map({
    "<30": 1,
    ">30": 0,
    "NO": 0
})

print(clean_df["readmitted_30"].value_counts())

readmitted_30
0    90409
1    11357
Name: count, dtype: int64

In [12]:
print("Identifier columns:")
print(clean_df[["encounter_id", "patient_nbr"]].head())

Identifier columns:
   encounter_id  patient_nbr
0       2278392      8222157
1        149190     55629189
2         64410     86047875
3        500364     82442376
4         16680     42519267

In [13]:
print("Final cleaned dataset shape:", clean_df.shape)

print("\nRemaining missing values:")
print(clean_df.isnull().sum().sum())

print("\nDuplicate rows:")
print(clean_df.duplicated().sum())

print("\nTarget distribution:")
print(clean_df["readmitted_30"].value_counts())

Final cleaned dataset shape: (101766, 46)

Remaining missing values:
0

Duplicate rows:
0

Target distribution:
readmitted_30
0    90409
1    11357
Name: count, dtype: int64

In [14]:
output_path = "/content/drive/MyDrive/Healthcare_Analytics/cleaned_diabetic_data.csv"

clean_df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")
print(output_path)

Cleaned dataset saved successfully!
/content/drive/MyDrive/Healthcare_Analytics/cleaned_diabetic_data.csv